### ISSUE TITLE
Upload Picture

### ISSUE THREAD

**Issue by saifudienrosyid** [wskurniawan/digtalent-be-11#2]
Permisi mas
Mas kalau eror di browser tertulis "Cannot read property 'photo' of undefined" di consolenya "File undefined"
bagaimana ya?

**Comment by saifudienrosyid** [comment]
tampilannya gini mas

![image](https://user-images.githubusercontent.com/72186628/95711531-270cbb80-0c8d-11eb-964a-121831f73d8d.png)

**Comment by saifudienrosyid** [comment]
gak jadi mas, sudah bisa.
Terima Kasih

**Comment by wskurniawan** [comment]
Okee maaf telat cek issue nya
